#!/bin/bash
#
# Format subplot (plentyfs.md), generate test program, and run it.

set -euo pipefail

cargo build
cargo test

subplot docgen plentyfs.md -o plentyfs.pdf
subplot docgen plentyfs.md -o plentyfs.html
subplot codegen plentyfs.md -o test.py
rm -f test.log
python3 test.py --log test.log
